language: node_js
node_js:
  - "node"
  - "lts/*"
services:
  - postgresql
env:
  - NODE_ENV=tests
install:
  - sudo pip install compare-locales
  - npm install
before_script:
  - compare-locales --validate l10n.toml .
  - compare-locales l10n.toml . `ls locales`
  - cp .env-dist .env
  - createdb test-blurts
  - npm install npm@latest -g
